### ISSUE TITLE
Flutterbum software license?

### ISSUE THREAD

**Issue by brylie** [mcknightg/flutterbum#1]
Thanks for this great demonstration app! I have started working through the videos, and would like to push my progress to a Github repository, but cannot find the original Flutterbum license to verify that permission. What is the software license for the Flutterbum application?

**Comment by mcknightg** [comment]
Hello,
I've added the least restrictive MIT license to the project.
Hope that helps.

Thanks for watching my videos.

George Mcknight

**Comment by brylie** [comment]
Great! I have created a [group repository](https://github.com/meteorcrowd/project-management). It is not a direct fork, as I am working through the videos. Thanks again George! :)

**Comment by brylie** [comment]
You might enjoy the album [Flutterspot - Suitable for a Desire to Share](http://flutterspot.bandcamp.com/). Cheers :-)

**Comment by mcknightg** [comment]
;)  Thanks for that.  It gives more credibility to the whole flutter thing.

BR,
George Mcknight
