### ISSUE TITLE
Flutterbum Chat: No way to submit

### ISSUE THREAD

**Issue by JustinWestphal** [mcknightg/flutterbum#11]
On the Flutterbum Dashboard (http://www.flutterbum.com/dashboard), the InterChat seems to be populated by some messages, but when typing and hitting enter, does not submit the message. Additionally there is no "Send" button or other way to submit.
![screen shot 2015-02-01 at 8 02 12 pm](https://cloud.githubusercontent.com/assets/2451149/5995622/3c9c6444-aa4d-11e4-9303-cbe968408f93.png)

**Comment by mcknightg** [comment]
Added submit button, and verified enter/return key submit.
