### ISSUE TITLE
Flutterbum Conversations: Doesn't seem to work as intended

### ISSUE THREAD

**Issue by JustinWestphal** [mcknightg/flutterbum#13]
After clicking the "Start a conversation" button, the dialogue pops up. 

Issue 1: the Cancel button doesn't work.

Issue 2: the X button in the corner doesn't work.

Issue 3: user can enter a blank message and save it. 

Issue 4: there is no character limit. Seems a system for showing only a snippet was supposed to go into place.

Issue 5: the conversation is a link, but doesn't do anything.

My assumption is that clicking the conversation snippet link should pop up a modal with a chat that keeps records of each message for that particular conversation. Nothing seems to work, however. Archiving works fine.

**Comment by mcknightg** [comment]
Fixed
