### ISSUE TITLE
Flutterbum: Archiving Projects

### ISSUE THREAD

**Issue by JustinWestphal** [mcknightg/flutterbum#16]
Issue 1: When user clicks the 'trash' icon on a project, in the modal dialogue that pops up, the 'Close' and 'X' buttons don't work.

Issue 2: Clicking 'OK' completely deletes the project. Shouldn't it Archive it, instead? This would be very bad for a company using this app to lose all records of finished projects, I think it should work more with the archiving system and you can see Completed Projects.

**Comment by mcknightg** [comment]
Fixed the Close and Cancel buttons.

**Comment by mcknightg** [comment]
I agree with your Archive statement, but whenever I exclude the delete functionality, I receive several emails asking how to delete. ;)

**Comment by JustinWestphal** [comment]
Haha fair enough! I’m still plugging away through the videos (which are great). After I build the app I plan to go through and custom design it, tweak some functionality, etc… so if I come up with any good solutions, I’ll let you know! Though of course I defer to your expertise :)

I admit though that as I watch you type, a lot of these functions seem like magic to me. Like “jeez, where does that come from?” Do you go through and read all the docs for every package, and for Meteor itself? Any recommended method for getting such familiarity with everything?

**Comment by mcknightg** [comment]
I definitely could do a better job slowing it down, and explaining more.  I familiarize myself by doing it over and over again.  I sit down with an idea, and say "how long will it take me to build a ..."  social app, project management, etc.  Then I build everything and trip several times before I figure out a good way.  Then... I have it down.
You will find the more times you type something, it becomes part of your vocabulary.

Thanks for all of the great comments.  I appreciate you helping me to make this better.
