### ISSUE TITLE
Error: EACCES, permission denied '/meteor_uploads'

### ISSUE THREAD

**Issue by brylie** [mcknightg/flutterbum#2]
I am having trouble getting the file uploads configuration to work. With the configuration shown in the video tutorial, I get the following error:

```
Error: EACCES, permission denied '/meteor_uploads'
```

Configuration:

```
Uploads = new FS.Collection('uploads',
                      {stores: [new FS.Store.FileSystem('uploads',
                               {path:'/meteor_uploads'})
                                 ] } );
```

Should I be using an absolute path?

**Comment by mcknightg** [comment]
I believe in the tutorial I used '~/meteor_uploads'  which indicates a folder in the current user home.  That folder has write permissions.  If you choose a different folder, you will need to make sure you "get info" and change the permissions to write.

**Comment by brylie** [comment]
On video tutorial "12. Start the Calendar Template" at _11:05_ you enter `/meteor_uploads` for the path. 

Also, the [uploads.js](https://github.com/mcknightg/flutterbum/blob/master/collections/uploads.js#L2) file on this repository has the same path string.

**Comment by mcknightg** [comment]
Sorry about that.  I've just changed the uploads.js file.  Were you able to get it working ?

**Comment by brylie** [comment]
I didn't see a part on the file event handling. 

It seems like the 'Start the Calendar View' lesson contains information about sections other than the Activities/Calendar. It might be worthwhile to break the 'Start the Calendar View' video into smaller segments, and see if anything is missing.

**Comment by brylie** [comment]
E.g. when did the tutorials demonstrate adding calendar events?

**Comment by mcknightg** [comment]
Calendar events added to video #13

**Comment by ThangDX** [comment]
Hi, I got stuck with video no.4 at Router. I think the boilerplate is updated  so it looks very differences from video so I want to clone your code and get it run to follow along with video.

I got the same problem with Error: EACCES, permission denied '/meteor_uploads' and cant find how to fix. can you please help?

**Comment by mcknightg** [comment]
Hi,
The issue is, that Meteor needs access to the folder you are writing to.
You can try changing the path to ~/meteor_uploads, since your home folder
probably already has write permissions enabled.  Otherwise, you can create
a folder, and set the permissions on the folder, so you can write to it.

Please let me know if this doesn't help.

Thanks
George Mcknight

**Comment by ThangDX** [comment]
Thank for prompt support, George. I got it and can run it on my local now.
