### ISSUE TITLE
 Cannot read property '_id' of undefined

### ISSUE THREAD

**Issue by ThangDX** [mcknightg/flutterbum#21]
Hi George,

I am at Video: Server Methods and got below error, can you please have look and help me how to fix it?

Thanks 

=> App running at: http://localhost:3000/
I20150306-13:34:27.073(7)? Exception while invoking method 'saveProject' TypeError: Cannot read property '_id' of undefined
I20150306-13:34:27.074(7)?     at [object Object].Meteor.methods.saveProject (app/server/email/config.js:29:54)
I20150306-13:34:27.074(7)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1599:1)
I20150306-13:34:27.075(7)?     at packages/ddp/livedata_server.js:648:1
I20150306-13:34:27.075(7)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150306-13:34:27.075(7)?     at packages/ddp/livedata_server.js:647:1
I20150306-13:34:27.075(7)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150306-13:34:27.075(7)?     at [object Object]._.extend.protocol_handlers.method (packages/ddp/livedata_server.js:646:1)
I20150306-13:34:27.075(7)?     at packages/ddp/livedata_server.js:546:1

**Comment by mcknightg** [comment]
Hi,
Do you have any customers in the customer collection ?
You will need at least one.

I put the following at the top of the file...
if(Customers.find().count() < 1){
    return Customers.insert({name:'House Account'});
  }

Thanks
George

**Comment by mcknightg** [comment]
Also, It looks like you are looking for id when you might need _id.

Thanks,
George

**Comment by ThangDX** [comment]
Thank George, I put above code then the last error clear but I still could not add project. Enter Project name then hit Enter but nothing happens. I check Robomongo then projects collection does not create. Any advice?

Here is my code, only route is different from yours:

email.js
//
 'saveProject': function(project) {
          check(project.name, String);
          project.userId = Meteor.userId();
          project.dateentered = new Date();
          project.lastupdate = new Date();
          if(!project.datedue) {
              project.datedue = new Date();
          }
          if(!project.customer){
              project.customer = Customers.findOne({})._id;
          }
          project.invited = [];
          return Projects.insert(project);
      }

dashboard.js
Template.dashboard.events({
    'keyup input[type=text]': function (event, tmpl) {
        if (event.which === 27 || event.which === 13) {
            event.preventDefault();
            var project = {};
            project.name = tmpl.find('#projectNameEnter').value;
            Meteor.call('saveProject', project);
        }
    }
});

routes.js

Router.configure({
    layoutTemplate: 'appLayout'
});

Router.route('/', {
  name: 'home'
});

Router.route('/dashboard', function () {
    this.render('dashboard', {
        waitOn: function() {
            return Meteor.subscribe('projects');
        },
        data: function() {
            return Projects.find();
        }
    })
});

Router.route('/customers');
Router.route('/archives');
Router.route('/roles');

publish.js
Meteor.publish('projects', function () {
    return Projects.find({});
})

**Comment by mcknightg** [comment]
and you have

<p>
        <input class="biginput" type="text" name="projectNameEnter" id="projectNameEnter" placeholder="Add A Project" value="">
      </p>

in the dashboard template html ?

Thanks
George

**Comment by ThangDX** [comment]
Yes, I have that code.

**Comment by mcknightg** [comment]
Can you put insecure and autopublish packages back to see if it’s a publish subscribe problem ?

meteor add autopublish
meteor add insecure

Thanks
George

**Comment by ThangDX** [comment]
I did added two but still not work. is my routes.js is correct? Thanks

**Comment by mcknightg** [comment]
Would it be possible that you zip the project and send to me, or put on github ?
It's hard to see where it could be going wrong.

**Comment by ThangDX** [comment]
here is my project github: https://github.com/ThangDX/meteorApp01.git

**Comment by mcknightg** [comment]
Can you try changing the routes.js to 
Router.map(function() {
this.route('home', {
    path: '/',
    layoutTemplate:'appLayout'
  });

this.route('dashboard',{ 
        path: '/dashboard',
        template: 'dashboard',
      waitOn: function() {
        return [Meteor.subscribe('projects')]
      },
      data: function() {
        return {
        projects : Projects.find()
      }
  }
});

this.route('/customers');
this.route('/archives');
this.route('/roles');

});

**Comment by mcknightg** [comment]
and config.js to 

Router.configure({
  controller: 'AppController',
  loadingTemplate: 'loading',
  layoutTemplate: 'appLayout'
});

// Router.plugin('loading', {loadingTemplate: 'loading'});
Router.plugin('dataNotFound', {dataNotFoundTemplate: 'notFound'});

**Comment by ThangDX** [comment]
Thanks, I will try this and let you know if it works.

**Comment by ThangDX** [comment]
Thanks George, it worked now.
