### ISSUE TITLE
{{ siteTitle}} does not work

### ISSUE THREAD

**Issue by cdsaidev** [mcknightg/flutterbum#23]
I have already added the ms-seo package back and put the seo.js back in the folder; but, it's not working.

**Comment by cdsaidev** [comment]
I cannot figure it out for the life of me!!

**Comment by mcknightg** [comment]
Have you tried placing the seo.js in the root folder (not inside client or server folders).

Meteor.startup(function() {
  if(Meteor.isClient) {
    SEO.config({
      title: 'Flutterbum',
      meta: {
        'description': 'Project Management Made Easy'
      },
      og: {
        'image': Meteor.absoluteUrl('share-image.png')
      },
      ignore: {
        meta: ['fragment', 'viewport', 'msapplication-TileColor', 'msapplication-TileImage', 'msapplication-config'],
        link: ['stylesheet', 'apple-touch-icon', 'rel', 'shortcut icon', 'icon']
      }
    });
  }
});

**Comment by cdsaidev** [comment]
Yeah, it's in the root;also in the second video i noticed your folder structured changed a bit. your routes.js file is now in the root folder. Here is my project: https://github.com/chris9753/flutterbum
Thx, in advance.

**Comment by mcknightg** [comment]
Ahh.  I see the problem.

In the https://github.com/mcknightg/flutterbum/blob/master/client/helpers/stringHelpers.js

Lines 1-3.  Should setup the helper.

**Comment by cdsaidev** [comment]
Hey, thx, but just wondering how come the videos don't reflect these changes?

**Comment by mcknightg** [comment]
I'm working on fixing those.  The problem is that I didn't make the
boilerplate, and it keeps changing.  I need to fork the git repository, and
use my own fork.
I've changed the boilerplate movies a few times to keep up, but they made
more drastic changes.
Once I have the remade videos, they will also become available.
