### ISSUE TITLE
Error invoking Method 'saveProject': Match failed [400] - similar to #27

### ISSUE THREAD

**Issue by nigelpasco** [mcknightg/flutterbum#28]
Hi. Neat tutorials, thank you very much... up until now I have managed to follow the vids, despite the changes to the boilerplate - for better or worse ;P 

I am having similar issue to fergvick's #27 - however with a [400] error. I have copied and pasted his code to double check any typos... but no difference. Any idea what the 400 error is due to?

Here is my saveProject method;

```
'saveProject':function(project){
check(project.name,String);
project.userId = Meteor.userId();
project.dateentered = new Date();
project.lastupdate = new Date();
if(!project.datedue){
  project.datedue = new Date();
}
if(!project.customer){
  project.customer = Customers.findOne({})._id;
}
project.invited = [];
return Projects.insert(project);
```

   }
Here is the template that calls it;

```
Template.dashboard.events({
'keyup input[type=text]': function(event,tmpl) {
if(event.which === 27 || event.which === 13){
  event.preventDefault();
  var project = {};
  project.name = tmpl.find('#projectNameEnter').value;
  Meteor.call('saveProject',project);
 }
 },
 });
```

Regards,

**Comment by nigelpasco** [comment]
git repo is here...
https://github.com/nigelpasco/flutterbum-10.git

**Comment by mcknightg** [comment]
Hi,

I had a look at your project.

There were a few problems.

in dashboard.html,
var project = []  should be var project = {}  - notice the curly braces,
not array brackets.

in the both/router/routes.js  You will need to subscribe, and set the data.

Router.route('/dashboard', {
  name: 'dashboard',
  controller: 'DashboardController',
  waitOn:function(){
    return Meteor.subscribe('projects');
  },
  data:{
    'projects':function(){
      return Projects.find();
    }
  }
});

Hope this helps.

George Mcknight

**Comment by nigelpasco** [comment]
Hey George, Thank you for reviewing that for me and the prompt response. Yes, the subscription from the dashboard router was what was required, well spotted. Much appreciated :+1:
