### ISSUE TITLE
Break 'Start the Calendar Template' video into smaller segments

### ISSUE THREAD

**Issue by brylie** [mcknightg/flutterbum#3]
The video 'Start the Calendar Template' is lengthy, and contains segments not related to the calendar functionality. It may also omit crucial functionality, necessary for subsequent videos.

**Comment by brylie** [comment]
E.g. after 6:49 the video starts to focus on conversations. In this section, the conversations template is created, but the functionality to add a conversation is not created.

**Comment by brylie** [comment]
10:29 begins a section on uploads, which finishes off the video (to 17:29). No mention is made of how to capture the file select event and upload the file.

**Comment by mcknightg** [comment]
I'm working on this now.  I should have it broken into smaller parts, and
any vague calendar detail resolved.
Thanks for your note.

**Comment by brylie** [comment]
Cheers! I am just noting these as issues, so that it is easy to keep track of the task :)

**Comment by mcknightg** [comment]
I've uploaded a new #13 video to include the Calendar functionality.
