### ISSUE TITLE
Missing Video Segments

### ISSUE THREAD

**Issue by JustinWestphal** [mcknightg/flutterbum#7]
Missing video segments ("hey wait when did he make that?") or explanations include:
1. Routing
2. Why are we adding methods to the email.js file?
3. Dashboard.html has a lot added between when we make it and when we see it again in Server Methods
4. onAfterAction says SEO.set, none of that is covered and SEO.js doesn't exist anymore.
5. 4:57 of Server Methods video what we make doesn't work the way it's shown on screen. Solved by commenting out this section of the save project code:
   
     // if(!project.client){
     //   project.client = Clients.findOne({})._id;
     // }

It was throwing errors about how the id is undefined.

**Comment by cdsaidev** [comment]
I second that ^ these videos need to be refactored and updated.
